version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 27015:27015
    links:
      - mongo
    networks:
      - mongo-compose-network
    container_name: mongo-express
    hostname: mongo-express

  mongo:
    image: mongo
    command: "--serviceExecutor adaptive --host 0.0.0.0"
    ports:
      - "27017:27017"   
    networks:
      - mongo-compose-network
    container_name: mongo
    hostname: mongo

networks: 
    mongo-compose-network:
      driver: bridge