version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      hostname: rabbitmq
      container_name: rabbitmq
      restart: always
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - distributed-estore
      volumes: 
        - rabbitmq:/home/raphael/Desenvolvimento/Docker/Volume/rabbitmq
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e296cd9f
    ports:
      - "27017:27017"
    volumes:
      - /home/raphael/Desenvolvimento/Docker/Volume/MongoDB/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: e296cd9f
      ME_CONFIG_MONGODB_PORT: 27017
     
    links:
      - mongo
    networks:
      - mongo-compose-network
      
networks: 
    mongo-compose-network:
      driver: bridge